FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

RUN npm install --omit=dev

# Copy all backend source code
COPY . .

# Expose backend port
EXPOSE 5000

# Start the server
CMD ["node", "server.js"]
