apiVersion: v1
kind: Service
metadata:
  name: quiz-backend-svc
  namespace: quizapp
spec:
  type: NodePort
  selector:
    app: quiz-backend
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30007