apiVersion: v1
kind: Service
metadata:
  name: quiz-frontend-svc
  namespace: quiz-app
spec:
  type: NodePort
  selector:
    app: quiz-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
