apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-frontend
  namespace: quizapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-frontend
  template:
    metadata:
      labels:
        app: quiz-frontend
    spec:
      containers:
      - name: frontend
        image: usairamsaeed/quiz-frontend:latest  # Corrected from localhost:5000
        ports:
        - containerPort: 80