
name: Build & Deploy to Minikube

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Docker for Minikube
        run: |
          eval $(minikube docker-env) || { echo "Failed to configure Docker for Minikube"; exit 1; }

      - name: Build & push backend
        run: |
          docker build -t usairamsaeed/quiz-backend:latest -f app/Dockerfile.backend .
          echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
          docker push usairamsaeed/quiz-backend:latest

      - name: Build & push frontend
        run: |
          docker build -t usairamsaeed/quiz-frontend:latest -f app/Dockerfile.frontend .
          echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
          docker push usairamsaeed/quiz-frontend:latest

      - name: Create namespace
        run: |
          kubectl create namespace quizapp --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f app/k8s/namespace.yaml -n quizapp
          kubectl apply -f app/k8s/backend-deployment.yaml -n quizapp
          kubectl apply -f app/k8s/backend-service.yaml -n quizapp
          kubectl apply -f app/k8s/frontend-deployment.yaml -n quizapp
          kubectl apply -f app/k8s/frontend-service.yaml -n quizapp

      - name: Verify deployment
        run: |
          kubectl get all -n quizapp -o wide